"""
compare_cohorts_ras_clean.py
============================
Re-analysis of RAS activation scores after removing Eisfeld ARHG-mutant patients
who ALSO carry somatic RAS pathway mutations.

Biological rationale:
  The core question is whether ARHG mutations (exchange factors / GTPase activating
  proteins) can activate RAS transcriptional programs INDEPENDENTLY of direct RAS
  pathway mutations.  Including patients who carry both an ARHG mutation AND a RAS
  pathway mutation confounds this question — their elevated RAS scores could simply
  reflect the co-occurring RAS mutation rather than any ARHG-driven effect.

  This script filters to the "RAS-clean" subset: ARHG-mutant patients with no
  somatic mutation in NRAS/KRAS/HRAS/PTPN11/NF1/CBL/RRAS/RRAS2/RAF1/BRAF/MAP2K1/MAP2K2.

Exclusion source:
  ras_pathway_mutants.csv — generated by ras_pathway_mutants.R from the full
  variant-level RDS.  One row per variant; patients to exclude are those with
  in_score_csv == TRUE (i.e., they have both a RAS mutation and an RNA-seq score).

Inputs:
  ras_activation_scores.csv          — BeatAML cohort (from ras_signature.py)
  applied_ras_scores.csv             — Eisfeld Lab ARHG-mutant (from apply_signature.py --normalize)
  ras_pathway_mutants.csv            — exclusion list (from ras_pathway_mutants.R)

Outputs:
  cohort_comparison_violin_rasclean.png
  cohort_comparison_boxplot_rasclean.png
  Printed: exclusion counts, per-patient RAS mutations, updated stats
"""

import os
from pathlib import Path
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import mannwhitneyu

# ===========================================================================
# PATHS
# ===========================================================================
OUTPUT_DIR = Path(os.environ.get("ARHG_BASE_DIR", str(Path(__file__).parent.parent.parent))) / "Ras Signature"
BEATAML_CSV   = OUTPUT_DIR / "ras_activation_scores.csv"
EISFELD_CSV   = OUTPUT_DIR / "applied_ras_scores.csv"
EXCLUSION_CSV = OUTPUT_DIR / "ras_pathway_mutants.csv"

# ===========================================================================
# LOAD DATA
# ===========================================================================
beataml    = pd.read_csv(BEATAML_CSV)
eisfeld    = pd.read_csv(EISFELD_CSV)
exclusions = pd.read_csv(EXCLUSION_CSV)

print("=" * 65)
print("compare_cohorts_ras_clean.py")
print("=" * 65)
print(f"\nLoaded {len(eisfeld)} Eisfeld ARHG-mutant scored samples")
print(f"Loaded {len(beataml)} BeatAML scored samples")
print(f"Loaded {len(exclusions)} rows from exclusion table ({exclusions['patient_id'].nunique()} patients)")

# ===========================================================================
# BUILD EXCLUSION SET
# Patients to exclude from the Eisfeld group:
#   in_score_csv == True → they have both a RAS mutation AND an RNA-seq score,
#   meaning they are present in applied_ras_scores.csv and must be removed.
# Patients with in_score_csv == False had no RNA-seq data and are already absent
# from applied_ras_scores.csv — no action needed for those.
# ===========================================================================
to_exclude = (
    exclusions[exclusions["in_score_csv"] == True]   # noqa: E712
    [["patient_id", "ras_score_id", "gene", "hgvs_mane", "vaf", "timepoint"]]
    .drop_duplicates(subset="ras_score_id")           # one row per patient
    .sort_values("ras_score_id")
)

exclude_ids = set(to_exclude["ras_score_id"].dropna())

print(f"\n{'─'*65}")
print("EXCLUSIONS — Eisfeld ARHG-mutant patients with somatic RAS pathway mutations")
print(f"{'─'*65}")
print(f"  Patients to exclude: {len(exclude_ids)}")
print()

for _, row in to_exclude.iterrows():
    # Find all RAS variants for this patient
    patient_variants = exclusions[exclusions["ras_score_id"] == row["ras_score_id"]]
    var_summary = "; ".join(
        f"{r['gene']} {r['hgvs_mane']} (VAF={r['vaf']:.3f}, {r['timepoint']})"
        for _, r in patient_variants.iterrows()
    )
    print(f"  EXCLUDE  {row['ras_score_id']}")
    print(f"           RAS mutations: {var_summary}")
    score = eisfeld.loc[eisfeld["sample_id"] == row["ras_score_id"], "RAS_score"]
    if len(score) > 0:
        print(f"           RAS score: {score.values[0]:.4f}")
    print()

# ===========================================================================
# FILTER EISFELD TO RAS-CLEAN SUBSET
# ===========================================================================
eisfeld_clean = eisfeld[~eisfeld["sample_id"].isin(exclude_ids)].copy()
n_original    = len(eisfeld)
n_excluded    = len(exclude_ids)
n_clean       = len(eisfeld_clean)

print(f"{'─'*65}")
print(f"  Original Eisfeld ARHG-mutant : {n_original}")
print(f"  Excluded (RAS co-mutated)    : {n_excluded}")
print(f"  RAS-clean subset             : {n_clean}")
print(f"{'─'*65}\n")

# Also report the 3 patients with RAS mutations who had no RNA-seq score
no_score = exclusions[exclusions["in_score_csv"] == False]["patient_id"].unique()  # noqa: E712
if len(no_score) > 0:
    print(f"Note: {len(no_score)} additional RAS-mutant patients ({', '.join(sorted(no_score))})")
    print(f"      had no RNA-seq data and were not in applied_ras_scores.csv.")
    print(f"      These are already absent from the analysis (no action needed).\n")

# ===========================================================================
# COMBINE FOR PLOTTING
# ===========================================================================
beataml_plot = beataml[["sample_id", "RAS_score", "group"]].copy()
eisfeld_plot = eisfeld_clean[["sample_id", "RAS_score"]].copy()
eisfeld_plot["group"] = "Eisfeld ARHG-mutant\n(RAS-clean)"

combined = pd.concat([beataml_plot, eisfeld_plot], ignore_index=True)

# Also keep a version with original label for side-by-side sanity check
eisfeld_orig = eisfeld[["sample_id", "RAS_score"]].copy()
eisfeld_orig["group"] = "Eisfeld ARHG-mutant\n(all, n=25)"

# ===========================================================================
# GROUP ORDER & COLORS
# ===========================================================================
GROUP_ORDER = [
    "RAS-mutant",
    "Eisfeld ARHG-mutant\n(RAS-clean)",
    "ARHG-mutant",      # BeatAML ARHG (underpowered — reference only)
    "Double-WT",
]
GROUP_ORDER = [g for g in GROUP_ORDER if g in combined["group"].unique()]

PALETTE = {
    "RAS-mutant"                      : "#E45756",   # red
    "Eisfeld ARHG-mutant\n(RAS-clean)": "#F28E2B",   # orange — primary result
    "ARHG-mutant"                      : "#76B7B2",   # muted teal — underpowered reference
    "Double-WT"                        : "#BAB0AC",   # grey
}

sns.set_style("whitegrid")
sns.set_context("paper", font_scale=1.3)

# ===========================================================================
# HELPER: draw significance bracket
# ===========================================================================
def draw_bracket(ax, x1, x2, y, p, tip=0.02):
    stars = "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 else "ns"
    ax.plot([x1, x1, x2, x2],
            [y, y + tip, y + tip, y],
            lw=1.2, color="black")
    ax.text((x1 + x2) / 2, y + tip + 0.005, stars,
            ha="center", va="bottom", fontsize=11)


# ===========================================================================
# PLOT 1 — Violin + strip (all groups)
# ===========================================================================
fig, ax = plt.subplots(figsize=(7, 5))

sns.violinplot(
    data=combined, x="group", y="RAS_score", hue="group",
    order=GROUP_ORDER, palette=PALETTE,
    inner=None, linewidth=0.8, alpha=0.55, legend=False, ax=ax,
)
sns.stripplot(
    data=combined, x="group", y="RAS_score", hue="group",
    order=GROUP_ORDER, palette=PALETTE,
    size=3, alpha=0.6, jitter=True, legend=False, ax=ax,
)

ax.axhline(0.5, color="black", linestyle="--", linewidth=1.0, alpha=0.5,
           label="Score = 0.5 threshold")
ax.legend(loc="upper right", fontsize=8)
ax.set_xlabel("")
ax.set_ylabel("RAS Activation Score")
ax.set_title(
    "RAS Pathway Activation — Eisfeld ARHG-mutant (RAS-clean) vs BeatAML Groups\n"
    f"(n={n_excluded} RAS co-mutated patients excluded; "
    f"BeatAML-trained LASSO; per-gene z-score normalized)"
)

# n= and % > 0.5 labels
for i, grp in enumerate(GROUP_ORDER):
    grp_scores = combined.loc[combined["group"] == grp, "RAS_score"]
    n   = len(grp_scores)
    pct = 100 * (grp_scores > 0.5).mean()
    ax.text(i, -0.07, f"n={n}\n{pct:.0f}% >0.5", ha="center", va="top",
            fontsize=8, transform=ax.get_xaxis_transform())

if "ARHG-mutant" in GROUP_ORDER:
    idx = GROUP_ORDER.index("ARHG-mutant")
    ax.text(idx, 1.02, "ref\n(BeatAML)", ha="center", va="bottom",
            fontsize=7, color="grey", transform=ax.get_xaxis_transform())

fig.tight_layout()
out1 = OUTPUT_DIR / "cohort_comparison_violin_rasclean.png"
fig.savefig(out1, dpi=150)
plt.close(fig)
print(f"Saved: {out1.name}")


# ===========================================================================
# PLOT 2 — Boxplot (3-group: RAS-mut, Eisfeld RAS-clean, Double-WT)
#           with significance brackets
# ===========================================================================
plot_groups = ["RAS-mutant", "Eisfeld ARHG-mutant\n(RAS-clean)", "Double-WT"]
plot_groups = [g for g in plot_groups if g in combined["group"].unique()]
plot_data   = combined[combined["group"].isin(plot_groups)].copy()

eisfeld_clean_scores = combined.loc[
    combined["group"] == "Eisfeld ARHG-mutant\n(RAS-clean)", "RAS_score"
]

fig, ax = plt.subplots(figsize=(6, 5))

sns.boxplot(
    data=plot_data, x="group", y="RAS_score", hue="group",
    order=plot_groups, palette=PALETTE,
    width=0.5, linewidth=1.2, fliersize=0, legend=False, ax=ax,
)
sns.stripplot(
    data=plot_data, x="group", y="RAS_score", hue="group",
    order=plot_groups, palette=PALETTE,
    size=3.5, alpha=0.55, jitter=True, legend=False, ax=ax,
)

ax.axhline(0.5, color="black", linestyle="--", linewidth=1.0, alpha=0.5,
           label="Score = 0.5 threshold")
ax.legend(loc="upper right", fontsize=8)

y_max = plot_data["RAS_score"].max()
eisfeld_idx = plot_groups.index("Eisfeld ARHG-mutant\n(RAS-clean)")

# Eisfeld RAS-clean vs RAS-mutant
if "RAS-mutant" in plot_groups:
    ras_idx = plot_groups.index("RAS-mutant")
    other   = combined.loc[combined["group"] == "RAS-mutant", "RAS_score"]
    _, p    = mannwhitneyu(eisfeld_clean_scores, other, alternative="two-sided")
    draw_bracket(ax, ras_idx, eisfeld_idx, y_max + 0.03, p)

# Eisfeld RAS-clean vs Double-WT
if "Double-WT" in plot_groups:
    wt_idx = plot_groups.index("Double-WT")
    other  = combined.loc[combined["group"] == "Double-WT", "RAS_score"]
    _, p   = mannwhitneyu(eisfeld_clean_scores, other, alternative="two-sided")
    draw_bracket(ax, eisfeld_idx, wt_idx, y_max + 0.12, p)

# n= labels
for i, grp in enumerate(plot_groups):
    n = (plot_data["group"] == grp).sum()
    ax.text(i, -0.07, f"n={n}", ha="center", va="top",
            fontsize=9, transform=ax.get_xaxis_transform())

# Annotate high scorers
n_high  = (eisfeld_clean_scores > 0.5).sum()
n_total = len(eisfeld_clean_scores)
ax.text(
    eisfeld_idx, y_max + 0.20,
    f"{n_high}/{n_total}\n>0.5",
    ha="center", va="bottom", fontsize=8,
    color=PALETTE["Eisfeld ARHG-mutant\n(RAS-clean)"],
    fontweight="bold",
)

ax.set_xlabel("")
ax.set_ylabel("RAS Activation Score")
ax.set_title(
    f"RAS Activation: ARHG-mutant (RAS-clean, n={n_clean}) vs BeatAML Groups\n"
    f"(n={n_excluded} RAS co-mutated excluded; dashed = 0.5 threshold)"
)
ax.set_ylim(bottom=-0.05, top=y_max + 0.35)

fig.tight_layout()
out2 = OUTPUT_DIR / "cohort_comparison_boxplot_rasclean.png"
fig.savefig(out2, dpi=150)
plt.close(fig)
print(f"Saved: {out2.name}")


# ===========================================================================
# PLOT 3 — Before/after panel (original vs RAS-clean side by side)
#           Shows explicitly how exclusion changes the distribution
# ===========================================================================
combined_ba = pd.concat([
    beataml[["sample_id", "RAS_score", "group"]],
    eisfeld_orig[["sample_id", "RAS_score", "group"]],
    eisfeld_plot[["sample_id", "RAS_score", "group"]],
], ignore_index=True)

ba_order = ["RAS-mutant", "Double-WT",
            "Eisfeld ARHG-mutant\n(all, n=25)",
            "Eisfeld ARHG-mutant\n(RAS-clean)"]
ba_order = [g for g in ba_order if g in combined_ba["group"].unique()]

ba_palette = {
    "RAS-mutant"                       : "#E45756",
    "Double-WT"                        : "#BAB0AC",
    "ARHG-mutant"                      : "#76B7B2",   # BeatAML ARHG reference
    "Eisfeld ARHG-mutant\n(all, n=25)" : "#AEC7E8",   # muted blue — pre-exclusion
    "Eisfeld ARHG-mutant\n(RAS-clean)" : "#F28E2B",   # orange — post-exclusion
}

fig, ax = plt.subplots(figsize=(8, 5))

sns.boxplot(
    data=combined_ba, x="group", y="RAS_score", hue="group",
    order=ba_order, palette=ba_palette,
    width=0.5, linewidth=1.2, fliersize=0, legend=False, ax=ax,
)
sns.stripplot(
    data=combined_ba, x="group", y="RAS_score", hue="group",
    order=ba_order, palette=ba_palette,
    size=3.5, alpha=0.6, jitter=True, legend=False, ax=ax,
)

ax.axhline(0.5, color="black", linestyle="--", linewidth=1.0, alpha=0.4)

for i, grp in enumerate(ba_order):
    scores = combined_ba.loc[combined_ba["group"] == grp, "RAS_score"]
    n   = len(scores)
    med = scores.median()
    ax.text(i, -0.07, f"n={n}\nmed={med:.2f}", ha="center", va="top",
            fontsize=7.5, transform=ax.get_xaxis_transform())

# Wilcoxon for both Eisfeld groups vs Double-WT
wt_scores = combined_ba.loc[combined_ba["group"] == "Double-WT", "RAS_score"]
y_top = combined_ba["RAS_score"].max()

if "Eisfeld ARHG-mutant\n(all, n=25)" in ba_order and "Double-WT" in ba_order:
    all_scores = combined_ba.loc[
        combined_ba["group"] == "Eisfeld ARHG-mutant\n(all, n=25)", "RAS_score"
    ]
    _, p = mannwhitneyu(all_scores, wt_scores, alternative="two-sided")
    all_idx = ba_order.index("Eisfeld ARHG-mutant\n(all, n=25)")
    wt_idx  = ba_order.index("Double-WT")
    draw_bracket(ax, wt_idx, all_idx, y_top + 0.03, p)

if "Eisfeld ARHG-mutant\n(RAS-clean)" in ba_order and "Double-WT" in ba_order:
    clean_scores = combined_ba.loc[
        combined_ba["group"] == "Eisfeld ARHG-mutant\n(RAS-clean)", "RAS_score"
    ]
    _, p = mannwhitneyu(clean_scores, wt_scores, alternative="two-sided")
    all_idx   = ba_order.index("Eisfeld ARHG-mutant\n(all, n=25)")
    clean_idx = ba_order.index("Eisfeld ARHG-mutant\n(RAS-clean)")
    draw_bracket(ax, all_idx, clean_idx, y_top + 0.03, p)

ax.set_xlabel("")
ax.set_ylabel("RAS Activation Score")
ax.set_title(
    "Before/After RAS Co-mutation Exclusion\n"
    f"(n={n_excluded} patients with somatic RAS pathway mutations removed)"
)
ax.set_ylim(bottom=-0.12, top=y_top + 0.35)

fig.tight_layout()
out3 = OUTPUT_DIR / "cohort_comparison_before_after.png"
fig.savefig(out3, dpi=150)
plt.close(fig)
print(f"Saved: {out3.name}")


# ===========================================================================
# WILCOXON SUMMARY TABLE
# ===========================================================================
print("\n" + "=" * 65)
print("WILCOXON TESTS — Eisfeld ARHG-mutant (RAS-clean)")
print(f"  n = {n_clean}")
print("=" * 65)

comparisons = [
    ("RAS-mutant", "vs RAS-mutant"),
    ("Double-WT",  "vs Double-WT"),
]
if "ARHG-mutant" in combined["group"].unique():
    comparisons.append(("ARHG-mutant", "vs BeatAML ARHG-mutant"))

for grp, label in comparisons:
    other_scores = combined.loc[combined["group"] == grp, "RAS_score"]
    if len(other_scores) == 0:
        continue
    stat, p = mannwhitneyu(eisfeld_clean_scores, other_scores, alternative="two-sided")
    stars   = "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 else "ns"
    print(f"  {label:<30} U={stat:.0f}, p={p:.4f} {stars}")


# ===========================================================================
# FULL GROUP SUMMARY
# ===========================================================================
print("\n" + "=" * 65)
print("GROUP SUMMARY")
print("=" * 65)
all_groups = list(combined["group"].unique()) + ["Eisfeld ARHG-mutant\n(all, n=25)"]
for grp in all_groups:
    src   = combined if "all" not in grp else combined_ba
    scores = src.loc[src["group"] == grp, "RAS_score"]
    if len(scores) == 0:
        continue
    marker = " <- RAS-clean (primary result)" if "RAS-clean" in grp else \
             " <- pre-exclusion comparison"   if "all"       in grp else ""
    print(f"  {grp.replace(chr(10), ' '):<42}  n={len(scores):3d}  "
          f"median={scores.median():.3f}  mean={scores.mean():.3f}{marker}")

print("=" * 65)
print(f"\nExcluded IDs: {sorted(exclude_ids)}")
print("\nDone. Plots saved to:", OUTPUT_DIR)
