#!/usr/bin/env bash
#SBATCH --job-name=star_align
#SBATCH --account=PAS1398
#SBATCH --partition=serial
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=40G
#SBATCH --time=4:00:00
#SBATCH --array=1-200%20
#SBATCH --output=/fs/ess/PAS1398/STAR_counts/logs/%A_%a.out
#SBATCH --error=/fs/ess/PAS1398/STAR_counts/logs/%A_%a.err

# ── CONFIGURE THESE BEFORE SUBMITTING ─────────────────────────────────────────
GENOME_DIR="/fs/ess/PAS1398/NCH Sequencing/references/GRCh38_STAR_index"
SAMPLE_LIST="$HOME/star_samples_expanded.tsv"               # generated by prep_star_samplelist.sh
OUT_BASE="/fs/ess/PAS1398/NCH Sequencing/references/star_output"
# ──────────────────────────────────────────────────────────────────────────────

module load STAR/2.7.11a-GCC-12.3.0

set -euo pipefail

mkdir -p "$OUT_BASE/logs"
mkdir -p "$OUT_BASE"

# Read this job's sample from the expanded list (skip header line)
LINE=$(sed -n "$((SLURM_ARRAY_TASK_ID + 1))p" "$SAMPLE_LIST")
if [[ -z "$LINE" ]]; then
    echo "No sample at index $SLURM_ARRAY_TASK_ID — exiting"
    exit 0
fi

SAMPLE_ID=$(echo "$LINE" | cut -f1)
RUN=$(echo      "$LINE" | cut -f2)
FASTQ_DIR=$(echo "$LINE" | cut -f3)

echo "=== STAR alignment ==="
echo "Sample:    $SAMPLE_ID"
echo "Run:       $RUN"
echo "FASTQ dir: $FASTQ_DIR"
echo "Date:      $(date)"

# ── Find FASTQs ────────────────────────────────────────────────────────────────
# Try R1/R2 paired-end first, fall back to single-end
R1=$(find "$FASTQ_DIR" -maxdepth 1 \( -name "*_R1_*.fastq.gz" -o -name "*_R1.fastq.gz" \
     -o -name "*_R1_*.fq.gz" -o -name "*_1.fastq.gz" \) 2>/dev/null | sort | tr '\n' ',' | sed 's/,$//')
R2=$(find "$FASTQ_DIR" -maxdepth 1 \( -name "*_R2_*.fastq.gz" -o -name "*_R2.fastq.gz" \
     -o -name "*_R2_*.fq.gz" -o -name "*_2.fastq.gz" \) 2>/dev/null | sort | tr '\n' ',' | sed 's/,$//')

if [[ -z "$R1" ]]; then
    echo "ERROR: No FASTQ files found in $FASTQ_DIR"
    exit 1
fi

if [[ -n "$R2" ]]; then
    echo "Mode: paired-end"
    READ_ARGS="--readFilesIn $R1 $R2"
else
    echo "Mode: single-end (no R2 found)"
    READ_ARGS="--readFilesIn $R1"
fi

echo "R1: $R1"
echo "R2: $R2"

# ── Output directory ───────────────────────────────────────────────────────────
OUT_DIR="$OUT_BASE/$RUN/$SAMPLE_ID"
mkdir -p "$OUT_DIR"

# Skip if already done
if [[ -f "$OUT_DIR/${SAMPLE_ID}_ReadsPerGene.out.tab" ]]; then
    echo "Already complete — skipping"
    exit 0
fi

# ── Run STAR ───────────────────────────────────────────────────────────────────
STAR \
    --runThreadN "$SLURM_CPUS_PER_TASK" \
    --genomeDir "$GENOME_DIR" \
    $READ_ARGS \
    --readFilesCommand zcat \
    --outSAMtype BAM SortedByCoordinate \
    --outSAMattributes NH HI AS NM MD \
    --quantMode GeneCounts \
    --outFileNamePrefix "$OUT_DIR/${SAMPLE_ID}_" \
    --outFilterMultimapNmax 20 \
    --alignSJoverhangMin 8 \
    --alignSJDBoverhangMin 1 \
    --outFilterMismatchNmax 999 \
    --outFilterMismatchNoverReadLmax 0.04 \
    --alignIntronMin 20 \
    --alignIntronMax 1000000 \
    --alignMatesGapMax 1000000

echo "=== Done: $(date) ==="
echo "Count file: $OUT_DIR/${SAMPLE_ID}_ReadsPerGene.out.tab"
